### ISSUE TITLE
Tags not available

### ISSUE THREAD

**Issue by ghost** [hostianer/HostiSocial#3]
alt and title-tag failed

**Comment by ChristopherDosin** [comment]
Since we are using `svg` Images we dont need an `alt` tag but i will add some `title` tags.

**Comment by ghost** [comment]
Hallo,

der angegeben Abstand oben funktioniert nicht. template cache, compiliert usw, durchgeführt.
firebug sagt:

<ul class="rrssb-buttons clearfix rrssb-1">
rrssb-buttons::after, .rrssb-buttons::before {
    content: " ";
    display: table;
}
.rrssb-buttons::after, .rrssb-buttons::before {
    content: " ";
    display: table;

**Comment by shyim** [comment]
Könntest du evtl. auch den Shopware Konfigurationsspeicher leeren und erneut kompelieren.
Falls es jedoch trotzdem nicht funktioniert, könntest du ein Link schicken um es genauer anzuschauen?

**Comment by ChristopherDosin** [comment]
Evtl. auch immer den Browser Cache leeren. Wie @Shyim sagte wäre auch ein Link hilfreich.

**Comment by ghost** [comment]
http://www.gesundwuerzen.de/store/gewuerzdose-edelstahl.html

**Comment by shyim** [comment]
http://i.imgur.com/mwacXUb.png

Das CSS ist da, jedoch verschiebt sich der Block erst ab 20px Höhe nach unten.
Das Element scheint den Abstand des oberen Elementes zu ignorieren.
Evtl weißt @kayyyy mehr drüber :)

Jedoch wenn du in den Einstellungen ein Wert über 20 nutzst, solltest du ein Unterschied bemerken :)

**Comment by ghost** [comment]
Der Wert ist auf 70 eingestellt...

**Comment by shyim** [comment]
Könnte man sich es evtl. mal via Teamviewer oder anderes anschauen?
Ich kann mir den Fehler gerade nicht erklären.
Habe auf der Demo-Seite es auf 70 gestellt, hat auch funktioniert. 

PS: Vielleicht solltest du bei Produktiv Betrieb die Source Maps deaktivieren, verdoppelt nur unnötig die CSS :)
